export const autConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCES: "USER_REGISTER_SUCCES",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};
export const categoryConstans = {
  GETT_ALL_CATEGORIES_REQUEST: "GETT_ALL_CATEGORIES_REQUEST",
  GETT_ALL_CATEGORIES_SUCCES: "GETT_ALL_CATEGORIES_SUCCES",
  GETT_ALL_CATEGORIES_FAILURE: "GETT_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCES: "ADD_NEW_CATEGORY_SUCCES",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  UPDATE_CATEGORIES_REQUEST:"UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCES:"UPDATE_CATEGORIES_SUCCES",
  UPDATE_CATEGORIES_FAILURE:"UPDATE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_REQUEST:"DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCES:"DELETE_CATEGORIES_SUCCES",
  DELETE_CATEGORIES_FAILURE:"DELETE_CATEGORIES_FAILURE"
};

export const productConstans = {
  GET_ALL_Products_REQUEST: "GET_ALL_Products_REQUEST",
  GET_ALL_Products_SUCCES: "GET_ALL_Products_SUCCES",
  GET_ALL_Products_FAILURE: "GET_ALL_Products_FAILURE",

  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};
export const initialDataConstans = {
  GET_ALL_INITIALDATA_REQUEST: "GET_ALL_INITIALDATA_REQUEST",
  GET_ALL_INITIALDATA_SUCCES: "GET_ALL_INITIALDATA_SUCCES",
  GET_ALL_INITIALDATA_FAILURE: "GET_ALL_INITIALDATA_FAILURE",
};
export const pageConstans ={
  CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
  CREATE_PAGE_SUCCES:'CREATE_PAGE_SUCCES',
  CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE',
}
export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};
export const adressConstants = {

  GETT_ALL_ADRES_SUCCES:'GETT_ALL_ADRES_SUCCES'
}